-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 22:23:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brothers
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `brothers` ;

-- -----------------------------------------------------
-- Schema brothers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brothers` DEFAULT CHARACTER SET utf8 ;
USE `brothers` ;

-- -----------------------------------------------------
-- Table `brothers`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`empleado` ;

CREATE TABLE IF NOT EXISTS `brothers`.`empleado` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `fecha_ingreso` DATE NULL,
  `tipo_empleado` ENUM('A', 'B') NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`clientes` ;

CREATE TABLE IF NOT EXISTS `brothers`.`clientes` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NULL,
  `fecha_registro` DATE NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`servicios` ;

CREATE TABLE IF NOT EXISTS `brothers`.`servicios` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `precio_unitario` DOUBLE NOT NULL,
  `duracion` INT NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`citas` ;

CREATE TABLE IF NOT EXISTS `brothers`.`citas` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `cliente` INT NOT NULL,
  `barbero` INT NOT NULL,
  `servicio` INT NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `cliente_idx` (`cliente` ASC) VISIBLE,
  INDEX `barbero_idx` (`barbero` ASC) VISIBLE,
  INDEX `servicio_idx` (`servicio` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `brothers`.`clientes` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `barbero`
    FOREIGN KEY (`barbero`)
    REFERENCES `brothers`.`empleado` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicio`
    FOREIGN KEY (`servicio`)
    REFERENCES `brothers`.`servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`promociones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`promociones` ;

CREATE TABLE IF NOT EXISTS `brothers`.`promociones` (
  `id_promocion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `descuento` DOUBLE NULL,
  `porcentaje` INT NULL,
  `inicio_vigencia` DATE NULL,
  `duracion` INT NULL,
  PRIMARY KEY (`id_promocion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`productos` ;

CREATE TABLE IF NOT EXISTS `brothers`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `precio_unitario` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`promociones_servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`promociones_servicios` ;

CREATE TABLE IF NOT EXISTS `brothers`.`promociones_servicios` (
  `promocion` INT NOT NULL,
  `servicio` INT NOT NULL,
  `cantidad` INT NULL,
  INDEX `promocion_idx` (`promocion` ASC) VISIBLE,
  INDEX `servicio_idx` (`servicio` ASC) VISIBLE,
  CONSTRAINT `promocion`
    FOREIGN KEY (`promocion`)
    REFERENCES `brothers`.`promociones` (`id_promocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicio`
    FOREIGN KEY (`servicio`)
    REFERENCES `brothers`.`servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`promociones_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`promociones_productos` ;

CREATE TABLE IF NOT EXISTS `brothers`.`promociones_productos` (
  `promocion` INT NOT NULL,
  `producto` INT NOT NULL,
  `cantidad` INT NULL,
  INDEX `promocion_idx` (`promocion` ASC) VISIBLE,
  INDEX `producto_idx` (`producto` ASC) VISIBLE,
  CONSTRAINT `promocion`
    FOREIGN KEY (`promocion`)
    REFERENCES `brothers`.`promociones` (`id_promocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`producto`)
    REFERENCES `brothers`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`ordenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`ordenes` ;

CREATE TABLE IF NOT EXISTS `brothers`.`ordenes` (
  `folio` VARCHAR(10) NOT NULL,
  `fecha` DATE NOT NULL,
  `barbero` INT NOT NULL,
  `servicio` INT NOT NULL,
  `promocion` INT NULL,
  `importe` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`folio`),
  INDEX `barbero_idx` (`barbero` ASC) VISIBLE,
  INDEX `servicio_idx` (`servicio` ASC) VISIBLE,
  INDEX `promocion_idx` (`promocion` ASC) VISIBLE,
  CONSTRAINT `barbero`
    FOREIGN KEY (`barbero`)
    REFERENCES `brothers`.`empleado` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicio`
    FOREIGN KEY (`servicio`)
    REFERENCES `brothers`.`servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `promocion`
    FOREIGN KEY (`promocion`)
    REFERENCES `brothers`.`promociones` (`id_promocion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brothers`.`ordenes_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `brothers`.`ordenes_productos` ;

CREATE TABLE IF NOT EXISTS `brothers`.`ordenes_productos` (
  `orden` VARCHAR(10) NOT NULL,
  `producto` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_total` DOUBLE NULL,
  INDEX `producto_idx` (`producto` ASC) VISIBLE,
  UNIQUE INDEX `orden_UNIQUE` (`orden` ASC) VISIBLE,
  CONSTRAINT `orden`
    FOREIGN KEY (`orden`)
    REFERENCES `brothers`.`ordenes` (`folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`producto`)
    REFERENCES `brothers`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
